 // for(i=secend;i<n-1;i++){
    //     for(j=secend;j<n-1-i;j++){
    //         if(array[j]>array[j+1]){
    //             temp=array[j];
    //             array[j]=array[j+1];
    //             array[j+1]=temp;
    //         }
    //     }
    // }